// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Domain.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Domain.EntityMap
{
    public class RoleMap
           :IEntityTypeConfiguration<Role>
      
    {
        public void Configure(EntityTypeBuilder<Role> builder)
        {
         // table
            builder.ToTable("sys_role");


            // Properties
            builder.Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            builder.Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(300)
                .IsRequired();
            builder.Property(t => t.Describe)
                .HasColumnName("Describe")
                .HasMaxLength(1500)
                ;
            builder.Property(t => t.CompanyId)
                .HasColumnName("CompanyId")
                ;
            builder.Property(t => t.CategoryId)
                .HasColumnName("CategoryId")
                ;
            builder.Property(t => t.Level)
                .HasColumnName("Level")
                .IsRequired();
            builder.Property(t => t.CreateTime)
                .HasColumnName("CreateTime")
                .IsRequired();
            builder.Property(t => t.UpdateTime)
                .HasColumnName("UpdateTime")
                .IsRequired();
            builder.Property(t => t.CreateUserId)
                .HasColumnName("CreateUserId")
                .IsRequired();
            builder.Property(t => t.UpdateUserId)
                .HasColumnName("UpdateUserId")
                .IsRequired();
            builder.Property(t => t.Status)
                .HasColumnName("Status")
                .IsRequired();
            builder.Property(t => t.SharedDataRoleIds)
               .HasColumnName("SharedDataRoleIds")
               .HasMaxLength(2000);

        }
    }
}
