// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Domain.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Domain.EntityMap
{
    public class UserRoleMap
           :IEntityTypeConfiguration<UserRole>
      
    {
        public void Configure(EntityTypeBuilder<UserRole> builder)
        {
         // table
            builder.ToTable("sys_userRole");


            // Properties
            builder.Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            builder.Property(t => t.UserId)
                .HasColumnName("UserId")
                .IsRequired();
            builder.Property(t => t.RoleId)
                .HasColumnName("RoleId")
                .IsRequired();

        }
    }
}
