//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Cloud.Domain.Entities;using Xg.Cloud.Core;

using System;
using Newtonsoft.Json;

namespace Domain.Entity
{
    /// <summary>
	/// sys_userRole
	/// </summary>
    public class UserRole:BaseEntity<long>
    {
        public UserRole()
        {
        }

        /// <summary>
	    /// 用户id
	    /// </summary>
       

        public long UserId { get; set; }
        /// <summary>
	    /// 角色id
	    /// </summary>
       

        public long RoleId { get; set; }

    }
}